server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/config-repo
          # ou utilise un repo GitHub :
          # uri: https://github.com/ton-username/config-repo
          default-label: main
